/**
 * This whole file is responsible for rendering the card onto the webpage.
 * Everything starts at the "Card" function at the bottom, where it intakes
 * settings (an object) and renders elements based on those settings. It 
 * currently renders three elements (h1, img, and p).

┌───────────────────────┐
│                       │
│ ┌───────────────────┐ │
│ │                   │ │ <- H1 element
│ │ Greeting Message  │ │
│ │                   │ │
│ └───────────────────┘ │
│                       │
│ ┌───────────────────┐ │
│ │                   │ │ <- IMG element
│ │                   │ │
│ │    The ICON       │ │
│ │                   │ │
│ │                   │ │
│ └───────────────────┘ │
│                       │
│ ┌───────────────────┐ │
│ │                   │ │ <- P element
│ │ A long message    │ │
│ │                   │ │
│ │                   │ │
│ │                   │ │
│ │                   │ │
│ │                   │ │
│ │                   │ │
│ └───────────────────┘ │
│                       │
└───────────────────────┘

 * The whole card gets styled inside of "Card.css," but each render function
 * will also carry it's own style based on the settings provided.
 */
import './Card.css';
import { deserialize } from './Customize';

const isEmpty = (str) => str === undefined || str.length === 0;
const getPattern = (id) => `/assets/transparent-textures/patterns/${id}.png`;
const getIcon = (id) => `https://dohliam.github.io/elegant-circles/svg/${id}.svg`;

/**
 * This will add an icon (img element) to the card.

┌───────────────────────┐
│                       │
│ ┌───────────────────┐ │
│ │                   │ │
│ │                   │ │
│ │    The ICON       │ │
│ │                   │ │
│ │                   │ │
│ └───────────────────┘ │
│                       │
└───────────────────────┘
 * @param {string} icon The icon name (not the URL to the icon)
 * @returns {ReactElement} an img element
 * Refer to: https://github.com/dohliam/elegant-circles
 * For the full list of icons, but the array "ICONS" (in Customize.jsx) are the
 * current options that the user has when generating a card.
 */
function renderIcon(icon) {
    let style = {};
    let srcUrl;
    if (isEmpty(icon)) {
        style.visibility = 'invisible';
        srcUrl = 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
    } else {
        srcUrl = getIcon(icon);
    }
    return <img src={srcUrl} alt='Card Icon' className='card-icon'></img>;
}

/**
 * This function will style the whole card; like the font family, font color,
 * background color, and pattern.
 * @param {string} font The font family (from settings)
 * @param {string} pattern The pattern name (from settings)
 * @param {object} color The color object (from settings)
 * @returns {object} An inline style object
 * Refer to: https://reactjs.org/docs/dom-elements.html#style
 * To see all of the options that can go into the style object.
 */
function getCardStyle(font, pattern, color) {
    let style = {};
    // Add pattern
    if (!isEmpty(pattern)) {
        const patternUrl = getPattern(pattern);
        style.backgroundImage = `url("${patternUrl}")`;
    }
    // Add font
    if (!isEmpty(font)) {
        style.fontFamily = font;
    }
    // Add color
    if (color !== undefined) {
        style.color = color.font;
        style.backgroundColor = color.primary;
    }

    return style;
}

/**
 * This function creates a style object for both the greeting message and
 * custom message that the user generated.
 * @param {object} color The color from settings
 * @returns {object}
 * Refer to: https://reactjs.org/docs/dom-elements.html#style
 * To see all of the options that can go into the style object.
┌───────────────────────┐
│                       │
│ ┌───────────────────┐ │
│ │                   │ │ <- This is getting styled
│ │ Greeting Message  │ │
│ │                   │ │
│ └───────────────────┘ │
│                       │
│ ┌───────────────────┐ │
│ │                   │ │ <- This also
│ │ A long message    │ │
│ │                   │ │
│ │                   │ │
│ │                   │ │
│ │                   │ │
│ │                   │ │
│ │                   │ │
│ └───────────────────┘ │
│                       │
└───────────────────────┘
 */
function getFontStyle(color) {
    let style = {};
    // Add color
    if (color !== undefined) {
        style.backgroundColor = color.secondary;
    }
    return style;
}

/**
 * This renders an empty card. A card without settings.
 * @returns {ReactElement}
 */
export default function DefaultCard() {
    try {
        return Card({});
    } catch (err) {
        console.error(err);
    }
}

/**
 * This decodes a base64 encoding of the settings generated by a user.
 * As an example:

# This is a base64 encoding

```
eyJtZXNzYWdlIjoiSGVsbG8gSSBob3BlIHlvdSBhcmUgZG9pbmcgd2VsbC4iLCJncmVldGluZyI6Ik
hlbGxvIFdvcmxkIiwiaWNvbiI6ImJpa2UiLCJjb2xvciI6eyJwcmltYXJ5IjoiIzYwNkMzOCIsInNl
Y29uZGFyeSI6IiMyODM2MTgiLCJmb250IjoiI0ZFRkFFMCJ9LCJmb250IjoiTG9ic3RlciIsInBhdH
Rlcm4iOiI0NS1kZWdyZWUtZmFicmljLWxpZ2h0In0
```

# This is the decoded version

```json
{
  "message": "Hello I hope you are doing well.",
  "greeting": "Hello World",
  "icon": "bike",
  "color": {
    "primary": "#606C38",
    "secondary": "#283618",
    "font": "#FEFAE0"
  },
  "font": "Lobster",
  "pattern": "45-degree-fabric-light"
}
```

 * The function then takes that JSON and provides it to the Card function as
 * valid settings for the card generation. 
 * @param {ReactPropTypes} props This allows us to give this function the 
 * encoded data.
 * @returns {ReactElement} The newly rendered card
 */
export function ImportCard(props) {
    console.debug(`Decoding "${props.encoded}"`);
    const settings = deserialize(props.encoded);
    console.debug('Decoded:', settings);
    try {
        return Card(settings);
    } catch (err) {
        console.error(err);
    }
}

/**
 * This renders a card based on the given settings.
 * @param {ReactElement} settings 
 * @returns {ReactElement}
 */
export function Card(settings) {
    const cardStyle = getCardStyle(settings.font, settings.pattern, settings.color);
    const fontStyle = getFontStyle(settings.color);

    const cardGreeting = <h1 style={fontStyle} className='card-greeting'>{settings.greeting}</h1>
    const cardIcon = renderIcon(settings.icon);
    const cardMsg = <p style={fontStyle} className="card-message">{settings.message}</p>

    const card = (
        <div style={cardStyle} className="card">
            {cardGreeting}
            {cardIcon}
            {cardMsg}
        </div>
    );

    return card;
}
